import type { Metadata } from "next";
import "./globals.css";
import { SpeechProvider } from "./utils/speechContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <SpeechProvider>
          {children}
        </SpeechProvider>
      </body>
    </html>
  );
}
