import type { Metadata } from "next";
import "./globals.css";
import { SpeechProvider } from "./utils/speechContext";
import { MessageProvider } from "./utils/messageContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative antialiased mx-auto max-w-xl">
        <SpeechProvider>
          <MessageProvider>{children}</MessageProvider>
        </SpeechProvider>
      </body>
    </html>
  );
}
